### PR TITLE
feat: added phone number extraction to pages.js

### PR DESCRIPTION
**Pull request by bryce-seefieldt**
Here is a starting point for [Issue 6](https://github.com/hammadsaedi/regex-pro/issues/6).

This currently reads up to 12 characters and extracts a 10-12 digit phone number.
I would really appreciate any guidance you can offer in terms of how you may want this regex to function.
For example do you want it to ignore all non-numeric characters?

Please advise on how I can improve or customize to your goals.  Thanks

### CODE REVIEW

**Comment by hammadsaedi** [comment]
It should have:
- country code (+92 / +123) or simple 0
- 10 Digits

image

should not extract

image

**Comment by bryce-seefieldt** [comment]
Ok thanks for the feedback. I’ll address this asap.

**Comment by bryce-seefieldt** [comment]
Updates made via new commit [c4c41bb](https://github.com/hammadsaedi/regex-pro/pull/32/commits/c4c41bbf63b31e18ea9e335d40a5f7215fb42afb). 
Please let me know if this works for you.

**Review by hammadsaedi — COMMENTED** [review]
Nailed!

**Pull request merged**
