### PR TITLE
feat: Made text area dynamic

### LINKED ISSUE #15: Textarea Should Not Display Scroll Bar and Automatically Resize
Currently, the textarea element displays a vertical scroll bar even when the text content does not exceed the visible area. Additionally, the textarea has a fixed size, which may not be ideal for dynamic or variable-length text. This issue is about addressing both of these concerns.

image

#### No Scroll Bar: 
The textarea should not display a vertical scroll bar when the text content does not exceed the visible area. In other words, if the content fits within the visible area, there should be no scroll bar visible to the user.

####  Dynamic Sizing: 
The textarea should automatically adjust its height to accommodate the content. When the user enters text, the textarea should expand vertically to display the entire text without the need for a scroll bar. Conversely, if the user deletes text, the textarea should shrink to fit the remaining content.

Proposed Solution:
To resolve this issue, you may consider using CSS to style the textarea with the following properties:

`textarea {`
  `overflow-y: hidden; /* Hide the vertical scroll bar */`
`  height: auto; /* Allow the textarea to adjust its height based on content */`
`}`
By applying these styles to the textarea, you can achieve the desired behavior. Additionally, you may need to handle the dynamic resizing of the textarea with JavaScript to ensure that it resizes based on the content entered by the user.

### PR DESCRIPTION
**Pull request by Virtual4087**
Fixes #15 

I've created a function that takes a text area as parameter and sets it's height according to the content inside it. This function is called every time a user inputs something in a text area.

### CODE REVIEW

**Comment by hammadsaedi** [comment]
I have checked these changes but the height is fixed. it's not changing.

## SS
image

**Comment by Virtual4087** [comment]
It was working on mine though but let me recheck it and I'll get back to you

**Comment by hammadsaedi** [comment]
sure :)

**Comment by Virtual4087** [comment]
Ohh my bad I only applied it to the Validation page, I'll change it.

**Comment by Virtual4087** [comment]
@hammadsaedi It should work fine now :)

**Comment by hammadsaedi** [comment]
Thanks for your contribution 🥇

**Pull request merged**
