### PR TITLE
PR #7: added sql_remover form

### PR DESCRIPTION
**Pull request by sfazli96**

### CODE REVIEW

**Comment by hammadsaedi** [comment]
It works for upper case but SQL is not case-sensitive. So, we have to take care of both cases.
image

**Comment by sfazli96** [comment]
Oh, ok so we want it to work for both uppercase and lowercase, correct? I can look into that and fix the issue. Thank you for something I missed.

**Comment by sfazli96** [comment]
Hi! I just updated the files and new commit that fixes the case-sensitive. Test it out. It is still in this pull request

**Comment by hammadsaedi** [comment]
Thanks :)

**Pull request merged**
